DCoL: Utils Class Reference
Utils Class Reference
Implements utilities.
#include <Utils.h>
Static Public Member Functions
static void setSeed (long seed)
static void generateNewRandomSeed ()
static float f_rand ()
static int i_rand (int lowV, int upV)
static float f_round (float lowV, int upV)
static bool readLine (std::ifstream &fin, std::string &line)
static bool isAComment (std::string &line)
static std::string trim (std::string &line)
static std::string removeFinalSpaces (std::string &line)
static void printParamsToFile (std::string fileName)
static void quickSort (float *vector, int *order, int i, int j)
static int partition (float *vector, int *order, int inf, int sup)
static void quickSort (Date *vector, int *order, int i, int j)
static int partition (Date *vector, int *order, int inf, int sup)
static void printGPLInformation (bool printWarrantyInfo, bool printRedistributionInfo)
static int min (int v1, int v2)
static int max (int v1, int v2)
static float min (float v1, float v2)
static float max (float v1, float v2)
static bool isNumeric (const char *line)
static int roundf (float num)
static void initLog (std::string fileName)
static void logWarningError (std::string logMessage)
static void closeLog ()
Static Public Attributes
static std::ofstream fLog
static bool doScreenStatistics
static const char REAL_ATTRIBUTE
static const char INTEGER_ATTRIBUTE
static const char NOMINAL_ATTRIBUTE
Detailed Description
Implements utilities.
This class implements several utilities such as sorting procedures, comparing procedures, and random seed initializers.
Author:
Albert Orriols-Puig and Nuria Macia
Grup de Recerca en Sistemes Intel.ligents
La Salle - Universitat Ramon Llull
C/ Quatre Camins, 2. 08022, Barcelona (Spain)
Date:
Created April, 2009
Last modified December, 2010
Copyright (C) 2009 Albert Orriols-Puig and Nuria Macia
This file is part of DCoL.
DCoL is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
DCoL is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with DCoL. If not, see <http://www.gnu.org/licenses/>.
Member Function Documentation
static void Utils::setSeed (long seed) [static]
Sets the seed of the random number generator.
Parameters:
seed is the seed.
static void Utils::generateNewRandomSeed () [static]
Generates a new random seed by taking the time of the system.
static float Utils::f_rand () [static]
Returns a continuous random number ranging between 0 and 1.
Returns:
A float with the random number.
static int Utils::i_rand (int lowV, int upV) [static]
Returns an integer random number ranging between lowV and upV.
Parameters:
lowV is the lower limit of the range.
upV is the upper limit of the range.
Returns:
An integer with the random number.
static float Utils::f_round (float lowV, int upV) [static]
Returns a continuous random number ranging between lowV and upV.
Parameters:
lowV is the lower limit of the range.
upV is the upper limit of the range.
Returns:
A float with the random number.
static bool Utils::readLine (std::ifstream & fin, std::string & line) [static]
Reads one line from file.
Parameters:
fin is the input file.
line is a string to store the line that will be read (passed by reference).
Returns:
A Boolean that indicates whether it is end of file.
Return values:
true end of file.
false not end of file yet.
static bool Utils::isAComment (std::string & line) [static]
Checks whether a line is a comment.
Parameters:
line is the line to be checked.
Returns:
A Boolean that indicates whether the line is a comment.
Return values:
true the line is a comment.
false the line contains useful data.
static std::string Utils::trim (std::string & line) [static]
Trims a string.
Parameters:
line is the string to be trimmed.
Returns:
A string with the trimmed string.
static std::string Utils::removeFinalSpaces (std::string & line) [static]
Removes the blank spaces at the end of the string.
Parameters:
line is the string to be processed.
Returns:
A string without blank spaces at the end.
static void Utils::printParamsToFile (std::string fileName) [static]
Prints the configuration parameters to file.
Parameters:
fileName is the name of the file where the parameters will be printed.
static void Utils::quickSort (float * vector, int * order, int i, int j) [static]
Implements the quicksort procedure for arrays of floats.
Parameters:
vector is the array to be sorted.
order is an auxiliary vector that needs to be sorted with the vector one.
i is the initial index from where the vector has to be sorted.
j is the final index until which the vector has to be sorted.
static int Utils::partition (float * vector, int * order, int inf, int sup) [static]
Implements an auxiliary function for quickSort for arrays of floats.
Parameters:
vector is the array to be sorted.
order is an auxiliary vector that needs to be sorted with the vector one.
inf is the initial index from where the vector has to be sorted.
sup is the final index until which the vector has to be sorted.
static void Utils::quickSort (Date * vector, int * order, int i, int j) [static]
Implements the quicksort procedure for arrays of Dates.
Parameters:
vector is the array to be sorted.
order is an auxiliary vector that needs to be sorted with the vector one.
i is the initial index from where the vector has to be sorted.
j is the final index until which the vector has to be sorted.
static int Utils::partition (Date * vector, int * order, int inf, int sup) [static]
Implements an auxiliary function for quickSort for arrays of Dates.
Parameters:
vector is the array to be sorted.
order is an auxiliary vector that needs to be sorted with the vector one.
inf is the initial index from where the vector has to be sorted.
sup is the final index until which the vector has to be sorted.
static void Utils::printGPLInformation (bool printWarrantyInfo, bool printRedistributionInfo) [static]
Prints information about the GPL license.
Parameters:
printWarrantyInfo is a Boolean that indicates whether warranty information has to be printed.
printRedistributionInfo is a Boolean that indicates whether redistribution information has to be printed.
static int Utils::min (int v1, int v2) [inline, static]
Returns the minimum value between the arguments.
Parameters:
v1 is the first integer.
v2 is the second integer.
Returns:
An integer with the minimum value between v1 and v2.
static int Utils::max (int v1, int v2) [inline, static]
Returns the maximum value between the arguments.
Parameters:
v1 is the first integer.
v2 is the second integer.
Returns:
An integer with the maximum value between v1 and v2.
static float Utils::min (float v1, float v2) [inline, static]
Returns the minimum value between the arguments.
Parameters:
v1 is the first float.
v2 is the second float.
Returns:
A float with the minimum value between v1 and v2.
static float Utils::max (float v1, float v2) [inline, static]
Returns the maximum value between the arguments.
Parameters:
v1 is the first float.
v2 is the second float.
Returns:
A float with the maximum value between v1 and v2.
static bool Utils::isNumeric (const char * line) [static]
Returns whether the passed string contains only numbers.
Parameters:
line is the input string.
Returns:
A Boolean that indicates whether the passed string contains only numbers.
Return values:
true the passed string contains only numbers.
false the passed string contains characters and may contain numbers as well.
static int Utils::roundf (float num) [inline, static]
Rounds the float to an integer.
Parameters:
num is the float number to be rounded.
Returns:
An integer with the rounded number.
static void Utils::initLog (std::string fileName) [inline, static]
Initializes the file for warning and error logging.
Parameters:
fileName is the name of the file.
References fLog.
static void Utils::logWarningError (std::string logMessage) [inline, static]
Writes the warning/error string to the log file.
Parameters:
logMessage is the string to be written.
References fLog.
Referenced by Vector< Etype >::firstElement(), HeapTree< Elem >::getElementAt(), and HeapTree< Elem >::getFirst().
static void Utils::closeLog () [inline, static]
Closes the log file.
References fLog.
Field Documentation
std::ofstream Utils::fLog [static]
File for warning and error logging.
Referenced by closeLog(), initLog(), and logWarningError().
bool Utils::doScreenStatistics [static]
Indicates whether screen statistics must be written.
const char Utils::REAL_ATTRIBUTE [static]
Identifies continuous attributes.
const char Utils::INTEGER_ATTRIBUTE [static]
Identifies integer attributes.
const char Utils::NOMINAL_ATTRIBUTE [static]
Identifies nominal attributes.
The documentation for this class was generated from the following file:
Utils.h